### ISSUE TITLE
undefined reference to `espconn_tcp_set_max_con'

### ISSUE THREAD

**Issue by bprzybyl** [earlephilhower/psychoplug#10]
Hi,
I tried the following:

1. Install esp8266/Arduino following "Using git version" including installing Arduino 1.8.2
2. from hardware/esp8266comm/esp8266 follow the commands from @earlephilhower at https://github.com/esp8266/Arduino/pull/3001 to checkout pull3001
3. follow remaing steps for psychoplug (generate SSL, 160Mhz, 1M 64k)

I cannot get it to compile and I get this:
```
sketch\psychoplug.ino.cpp.o: In function `StartSTA()':

C:\Users\brook\OneDrive\Documents\Arduino\psychoplug/psychoplug.ino:171: undefined reference to `espconn_tcp_set_max_con'

C:\Users\brook\OneDrive\Documents\Arduino\psychoplug/psychoplug.ino:171: undefined reference to `espconn_tcp_get_max_con'

C:\Users\brook\OneDrive\Documents\Arduino\psychoplug/psychoplug.ino:174: undefined reference to `espconn_tcp_set_max_con'

C:\Users\brook\OneDrive\Documents\Arduino\psychoplug/psychoplug.ino:181: undefined reference to `espconn_tcp_get_max_con'

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Generic ESP8266 Module.
```

Am I doing something incorrectly?

**Comment by earlephilhower** [comment]
No, I think they have just updated the SDK on the git repo and this new one doesn't export that function.

Simply comment or those lines in the main sketch, they are optional hints, anyway, for the TCP stack.

Let me know if anything else isn't compiling with the new repo.

Thanks,
-EFP3

**Comment by earlephilhower** [comment]
Just committed that change to the repo.  Closing.
