### ISSUE TITLE
Can't connect to wifi

### ISSUE THREAD

**Issue by lodesmets** [earlephilhower/psychoplug#11]
I've done everything as described (even the thing from issue #10). But The program doesn't want to connect to my wifi.
The program is stuck in "000000: Trying to connect to '******' key '*********'"  (I blanked out wifi and pw)
I tried another program (example program) and for some reason that connects without problem
I use a nodeMCU V3 (esp8266) 
I tried it with different wifi routers

**Comment by earlephilhower** [comment]
Unfortunately that's part of the standard library.  Do you have a password with any special characters, or maybe no password?  I may be recording it improperly in "EEPROM," so the connection after reboot won't match.  Passwords with HTML form special characters (ampersand, question mark, pound) may be the most susceptible, does that match yours?

**Comment by earlephilhower** [comment]
Can you try commenting out lines 167 and 168 in the main psychoplug.ino file (Wifi.config(zero,zero,zero,zero))?

I use hardcoded IPs for all of my plugs and SDK v2.3 (one for the fish tank, one for landscape lights, and a couple for Christmas lights), but it looks like the 2.4rc2 builds of the SDK changed the behaviour of the .config() method.  In 2.3 setting the IP to 0.0.0.0 was the way to reliably ensure a DHCP request when you had set a static IP on a prior connection, but in 2.4 it seems to actually try and request that IP (which is obviously invalid).

**Comment by lodesmets** [comment]
It works now, commenting line 167 and 168
The SSID had a _ in it. But I don't think that was the problem
