### ISSUE TITLE
Compilation issues in arduino IDE

### ISSUE THREAD

**Issue by bradc87** [earlephilhower/psychoplug#12]
Getting these messages at compile time

Arduino: 1.8.5 (Linux), Board: "WeMos D1 R2 & mini, 80 MHz, 4M (1M SPIFFS), v2 Prebuilt (MSS=536), Disabled, None, 115200"

WARNING: Spurious .circleci folder in 'Homie' library
psychoplug:67: error: 'WiFiServerSecure' does not name a type
 static WiFiServerSecure https(443);
        ^
/home/brad/PPlug/psychoplug/psychoplug.ino: In function 'void StartSetupAP()':
psychoplug:150: error: 'https' was not declared in this scope
   https.begin();
   ^
/home/brad/PPlug/psychoplug/psychoplug.ino: In function 'void StartSTA()':
psychoplug:193: error: 'https' was not declared in this scope
   https.begin();
   ^
/home/brad/PPlug/psychoplug/psychoplug.ino: In function 'void setup()':
psychoplug:416: error: 'https' was not declared in this scope
   https.setServerKeyAndCert_P(rsakey, sizeof(rsakey), x509, sizeof(x509));
   ^
/home/brad/PPlug/psychoplug/psychoplug.ino: In function 'void loop()':
psychoplug:695: error: 'https' was not declared in this scope
     WiFiClientSecure client = https.available();
                               ^
psychoplug:716: error: 'https' was not declared in this scope
     WiFiClientSecure client = https.available();
                               ^
exit status 1
'WiFiServerSecure' does not name a type

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by earlephilhower** [comment]
You need use git head to get the HTTPS server code.  You should use it anyway, as 2.4.0 had some issues w/simple WiFi as well.
