### ISSUE TITLE
Issue with "current time"

### ISSUE THREAD

**Issue by gszakacs** [earlephilhower/psychoplug#13]
Hi, I have a few ecoplugs laying around and always wanted to change them from using the original firmware for various reasons. Psychoplug has all those features I have been looking for (access using a browser, programmable timer, mqtt). However, after uploading the psychoplug firmware to the ecoplug, on 24-JUN-2018, at 10:23 PM (widows time), the devices built-in web server is displaying 1:32 AM EST, Sunday 7/2/2106.  Could you point me to the .h or cpp file where I need to make the change to fix the issue. Thanks

**Comment by earlephilhower** [comment]
Go to the setup html page, there is a popup where you can pick the proper timezone and have the plug reboot.

**Comment by gszakacs** [comment]
I tried 3 different time zones before submitting the issue. In one of the EU time zones the date set itself to 1970, in my time zone (US ET), the date is running 82 years ahead. When is it required to run the perl script that's related to the time zones ? Thx

**Comment by gszakacs** [comment]
Never mind. My firewall was blocking incoming/outgoing udp 123 (ntp) requests. After allowing udp 123, the time/event scheduler is running great. Almost ready to flash this on all my other esp8266 outlets,just need the mqtt remotepower function to work properly (/event, /powerstate, /button topics all work great.

**Comment by earlephilhower** [comment]
Sounds like it's OK now, closing this.  The MQTT stuff was tracked (and I hope fixed) in a separate issue.
