### ISSUE TITLE
can't compile, missing key.h  ???

### ISSUE THREAD

**Issue by RudyFiero** [earlephilhower/psychoplug#3]
It wouldn't compile 

C:\Users\Rudy\Documents\Arduino\esp8266\psychoplug\psychoplug.ino:58:17: fatal error: key.h: No such file or directory

 #include "key.h"

                 ^
compilation terminated.

But I did a search for   #include "key.h"   and I couldn't find it.  The only place I found the word key was in the two mqtt files. But no include statement. Maybe in a library?

C:\Users\Rudy\Documents\Arduino\esp8266\psychoplug\psychoplug.ino:58:17: fatal error: key.h: No such file or directory

 #include "key.h"

                 ^

compilation terminated.

Using library ESP8266WiFi at version 1.0 in folder: C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\libraries\ESP8266WiFi 
Using library ESP8266WebServer at version 1.0 in folder: C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\libraries\ESP8266WebServer 
Using library ESP8266HTTPUpdateServer at version 1.0 in folder: C:\Program Files (x86)\Arduino\hardware\esp8266com\esp8266\libraries\ESP8266HTTPUpdateServer 
Using library Time at version 1.5 in folder: C:\Users\Rudy\Documents\Arduino\libraries\Time 
exit status 1
Error compiling for board Generic ESP8266 Module.

**Comment by ebina1** [comment]
I created key.h by running make-certs-256.sh in the psychoplug directory on my linux machine

**Comment by earlephilhower** [comment]
Howdy,

The generated key.h should be placed in the same directory as the other source files.  Is it in the same dir as the psychoplug.ino file?  You'd also need, obviously, to have the read permissions set properly (if, say, you made it as root and it's set 700 umode...).

If it's there, then maybe this related to a difference between Windows and Linux with regards to include search paths.  In that case can you try making that line "#include "./key.h" (or #include ".\key.h" if the compiler there needs DOS path separators) and report if that helps?  I'm disinclined to think it's this, as all the other #includes would fail as well, though...

Thx
-EFP3

**Comment by earlephilhower** [comment]
Oh, one other thing.  Since your "key.h" was made on Linux the line endings may not work w/the Windows compiler.  Under Linux there's a tool, "unix2dos" which can convert the \r into a \r\n for Windows.  Notepad++ or other Windows editors should also be able to do the conversion for you.

**Comment by earlephilhower** [comment]
Closing as this just needs to have the user generate their own key using the script.

**Comment by RudyFiero** [comment]
The problem is that you provided no information on the what the key.h is and what anyone using your program should do to find out what they need to do. I followed the documentation on the root page and it didn't work. And there was nothing there to indicate what was needed.

**Comment by earlephilhower** [comment]
Wow, you're absolutely right!  I thought I had this here, but it seems I only added documentation in the PR to the main Arduino libraries.  My mistake, and I do appreciate the notice.  Sometimes you stare so long at code you no longer see what's really there...

Just added a section on this to the readme.md
