### ISSUE TITLE
wget needs --auth-no-challenge due to Connection: keep-alive request

### ISSUE THREAD

**Issue by ebina1** [earlephilhower/psychoplug#4]
To turn the plug on 
wget --user=username --password=mypass "https://..../on.html"
didn't work, I had to use:
wget --no-check-certificate --auth-no-challenge --user=username --password=mypass "https://.../on.html
The man page for wget says:
--auth-no-challenge
           If this option is given, Wget will send Basic HTTP authentication
           information (plaintext username and password) for all requests,
           just like Wget 1.10.2 and prior did by default.

           Use of this option is not recommended, and is intended only to
           support some few obscure servers, which never send HTTP
           authentication challenges, but accept unsolicited auth info, say,
           in addition to form-based authentication

Since this option is not recommended it seems like the server should be "fixed"

**Comment by earlephilhower** [comment]
Howdy,

Thanks for the report!  Can you try it with just the --no-check-certificate?  FWIW, even if wget does require sending plaintext user/pass to the plug (I'll scan the code to check later, not sure what protocol error this could be referring to), because you're on a SSL connection those plaintext password/username are encrypted anyway.  HTTP basic authentication is going to send plaintext no matter what (well, base64 encoded which is NOT encrypted) you do, which is the real reason you want SSL/https for all web logins.

I was able to get an OK response with the following line.  The warning is related to the self-signed cert's IP (127.0.0.1) not matching my fish plug's final IP.  This could be fixed by changing the make-self-cert.sh script reflect the proper IP, but it's something I didn't bother on my own network...

earle@server:/tmp$ wget --no-check-certificate --user=username --password=mypass https://192.168.1.28/on.html
--2017-05-23 19:46:11--  https://192.168.1.28/on.html
Connecting to 192.168.1.28:443... connected.
WARNING: cannot verify 192.168.1.28's certificate, issued by ‘CN=127.0.0.1,O=psychoplug’:
  Self-signed certificate encountered.
    WARNING: certificate common name ‘127.0.0.1’ doesn't match requested host name ‘192.168.1.28’.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘on.html.1’

on.html.1                                          [ <=>                                                                                                 ]     293  --.-KB/s    in 0.02s   

2017-05-23 19:46:12 (12.7 KB/s) - ‘on.html.1’ saved [293]

**Comment by ebina1** [comment]
Could you possibly be using a version of wget that is 1.10.2 or older?  As indicated in the man page, then it does --auth-no-challenge by default.
My wget is 1.15 and definitely won't work without the --auth-no-challenge option.

```
$ wget --no-check-certificate --user=admin --password=testing  https://192.168.0.7/on.html
--2017-05-23 22:29:51--  https://192.168.0.7/on.html
Connecting to 192.168.0.7:443... connected.
WARNING: cannot verify 192.168.0.7's certificate, issued by ‘/O=psychoplug/CN=127.0.0.1’:
  Self-signed certificate encountered.
    WARNING: certificate common name ‘127.0.0.1’ doesn't match requested host name ‘192.168.0.7’.
HTTP request sent, awaiting response... 401 
Reusing existing connection to 192.168.0.7:443.
HTTP request sent, awaiting response... 200 No headers, assuming HTTP/0.9
Length: unspecified
Saving to: ‘on.html’

    [ <=>                                   ] 269         --.-K/s   in 0.07s   

2017-05-23 22:29:51 (3.58 KB/s) - ‘on.html’ saved [269]
```

```
$ cat on.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><html><head><title>401 Unauthorized</title><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
<body><h1>401 Unauthorized</h1></body></html>
```

**Comment by earlephilhower** [comment]
Hmm.  I believe  your output but on 1.17 it isn't giving me any trouble at all.  Can you supply the version number you have?  I'm running the Ubuntu 16.04 latest patch level.

earle@server:~$ wget --version
GNU Wget 1.17.1 built on linux-gnu.
 
+digest -gpgme +https +ipv6 +iri +large-file -metalink +nls +ntlm
+opie -psl +ssl/openssl
 ...

I'll need to read up on this to understand what wget is actually complaining about. As I had to roll my own authentication and web server I'm sure there are bugs, but I've never seen anything like this...I probably want to include some headers on error responded for starters, but that's a secondary thing here.

**Comment by ebina1** [comment]
$ wget --version
GNU Wget 1.15 built on linux-gnu.

+digest +https +ipv6 +iri +large-file +nls +ntlm +opie +ssl/openssl

**Comment by earlephilhower** [comment]
Thanks.  I'll try to build that specific wget version this weekend on my own system and give it a try.

I'm really confused about your original output.  It's saying something that can't actually happen has happened, namely that no headers were sent:
$ wget --no-check-certificate --user=admin --password=testing  https://192.168.0.7/on.html
--2017-05-23 22:29:51--  https://192.168.0.7/on.html
...
`HTTP request sent, awaiting response... **200 No headers, assuming HTTP/0.9**`
...

The code that handles the authorized/unauthorized path is in web.cpp:
```
if (!authBuff[0] || !matchUser || !matchPass) {
      LogPrintf("WebReadRequest: Unauthenticated\n");
      WebError(client, 401, PSTR("WWW-Authenticate: Basic realm=\"PsychoPlug\""));
      return false;
}
```

So if there's no basic-authenticate or a password mismatch you get sent to WebError, which is:
```
void WebError(WiFiClient *client, int code, const char *headers, bool usePMEM)
{
  LogPrintf("+WebError: Begin, free=%d\n", ESP.getFreeHeap());
  WebPrintf(client, "HTTP/1.1 %d\r\n", code);
  WebPrintf(client, "Server: PsychoPlug\r\n");
  ...
```

That's obviously returning a set HTTP headers.

Very odd!

**Comment by ebina1** [comment]
Here it is failing with --debug in wget for a little more info:

```
$ wget --debug --no-check-certificate --user=admin --password=testing  https://192.168.0.7/on.html
Setting --check-certificate (checkcertificate) to 0
Setting --user (user) to admin
Setting --password (password) to testing
DEBUG output created by Wget 1.15 on linux-gnu.

URI encoding = ‘UTF-8’
--2017-05-24 15:48:10--  https://192.168.0.7/on.html
Host ‘192.168.0.7’ has not issued a general basic challenge.
Connecting to 192.168.0.7:443... connected.
Created socket 3.
Releasing 0x0000000002462310 (new refcount 0).
Deleting unused 0x0000000002462310.
Initiating SSL handshake.
Handshake successful; connected socket 3 to SSL handle 0x0000000002462360
certificate:
  subject: /O=psychoplug/CN=127.0.0.1
  issuer:  /O=psychoplug/CN=127.0.0.1
WARNING: cannot verify 192.168.0.7's certificate, issued by ‘/O=psychoplug/CN=127.0.0.1’:
  Self-signed certificate encountered.
    WARNING: certificate common name ‘127.0.0.1’ doesn't match requested host name ‘192.168.0.7’.

---request begin---
GET /on.html HTTP/1.1
User-Agent: Wget/1.15 (linux-gnu)
Accept: */*
Host: 192.168.0.7
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response... 
---response begin---
HTTP/1.1 401
Server: PsychoPlug
Content-type: text/html
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
WWW-Authenticate: Basic realm="PsychoPlug"

---response end---
401 
Registered socket 3 for persistent reuse.
] done.
Inserted ‘192.168.0.7’ into basic_authed_hosts
Reusing existing connection to 192.168.0.7:443.
Reusing fd 3.

---request begin---
GET /on.html HTTP/1.1
User-Agent: Wget/1.15 (linux-gnu)
Accept: */*
Host: 192.168.0.7
Connection: Keep-Alive
Authorization: Basic YWRtaW46dGVzdGluZw==

---request end---
HTTP request sent, awaiting response... 
---response begin---
---response end---
200 No headers, assuming HTTP/0.9
Length: unspecified
Saving to: ‘on.html’

    [ <=>                                   ] 269         --.-K/s   in 0.08s   

2017-05-24 15:48:11 (3.45 KB/s) - ‘on.html’ saved [269]

```

**Comment by ebina1** [comment]
Here is the same thing with curl, which does work.

```
$ curl --verbose --insecure --user admin:testing https://192.168.0.7/on.html
* Hostname was NOT found in DNS cache
*   Trying 192.168.0.7...
* Connected to 192.168.0.7 (192.168.0.7) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using AES256-SHA256
* Server certificate:
* 	 subject: O=psychoplug; CN=127.0.0.1
* 	 start date: 2017-05-23 05:31:27 GMT
* 	 expire date: 2031-01-30 05:31:27 GMT
* 	 issuer: O=psychoplug; CN=127.0.0.1
* 	 SSL certificate verify result: self signed certificate (18), continuing anyway.
* Server auth using Basic with user 'admin'
> GET /on.html HTTP/1.1
> Authorization: Basic YWRtaW46dGVzdGluZw==
> User-Agent: curl/7.35.0
> Host: 192.168.0.7
> Accept: */*
> 
< HTTP/1.1 200 OK
* Server PsychoPlug is not blacklisted
< Server: PsychoPlug
< Content-type: text/html
< Cache-Control: no-cache, no-store, must-revalidate
< Pragma: no-cache
< Expires: 0
< Refresh: 1; url=index.html
* no chunk, no close, no size. Assume close to signal end
< 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><html><head><title>Success</title><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
* Closing connection 0
* SSLv3, TLS alert, Client hello (1):
</head><body><h1><a href="index.html">Success.  Click here if not auto-refreshed</a></h1>
```

**Comment by earlephilhower** [comment]
Wonderful, thanks!  This will help immensely!

**Comment by earlephilhower** [comment]
Figured it out.  Turns out that WGET will try and reuse the connection after a failed request, and that just isn't going to work for us.  By adding the Connection: close header to all responses we let WGET know to not try this.
```

earle@server:~/Arduino/psychoplug$ wget --no-check-certificate --user=admin --password=pass https://192.168.1.36/on.html -O- --verbose
--2017-05-27 14:59:25--  https://192.168.1.36/on.html
Connecting to 192.168.1.36:443... connected.
WARNING: cannot verify 192.168.1.36's certificate, issued by ‘CN=127.0.0.1,O=psychoplug’:
  Self-signed certificate encountered.
    WARNING: certificate common name ‘127.0.0.1’ doesn't match requested host name ‘192.168.1.36’.
HTTP request sent, awaiting response... 401 
Authentication selected: Basic realm="PsychoPlug"
Connecting to 192.168.1.36:443... connected.
WARNING: cannot verify 192.168.1.36's certificate, issued by ‘CN=127.0.0.1,O=psychoplug’:
  Self-signed certificate encountered.
    WARNING: certificate common name ‘127.0.0.1’ doesn't match requested host name ‘192.168.1.36’.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘STDOUT’

-                                              [<=>                                                                                   ]       0  --.-KB/s               <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><html><head><title>Success</title><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
-                                              [ <=>                                                                                  ]     293  --.-KB/s    in 0.03s   

2017-05-27 14:59:27 (9.98 KB/s) - written to stdout [293]

```

**Comment by earlephilhower** [comment]
Oh yeah, the latest commit has this change, of course.  The ZIP file in your other bug report doesn't have this change, it was done before this change, obviously.

**Comment by ebina1** [comment]
Sadly still not working for me, in this debug output you can see, it is getting the Connection:close header, and still is reusing the connection

```
$wget --debug --no-check-certificate  --user=admin --password=testing  https://192.168.0.7/on.html
Setting --check-certificate (checkcertificate) to 0
Setting --user (user) to admin
Setting --password (password) to testing
DEBUG output created by Wget 1.15 on linux-gnu.

URI encoding = ‘UTF-8’
--2017-05-27 20:57:18--  https://192.168.0.7/on.html
Host ‘192.168.0.7’ has not issued a general basic challenge.
Connecting to 192.168.0.7:443... connected.
Created socket 3.
Releasing 0x00000000020a1310 (new refcount 0).
Deleting unused 0x00000000020a1310.
Initiating SSL handshake.
Handshake successful; connected socket 3 to SSL handle 0x00000000020a1360
certificate:
  subject: /O=psychoplug/CN=127.0.0.1
  issuer:  /O=psychoplug/CN=127.0.0.1
WARNING: cannot verify 192.168.0.7's certificate, issued by ‘/O=psychoplug/CN=127.0.0.1’:
  Self-signed certificate encountered.
    WARNING: certificate common name ‘127.0.0.1’ doesn't match requested host name ‘192.168.0.7’.

---request begin---
GET /on.html HTTP/1.1
User-Agent: Wget/1.15 (linux-gnu)
Accept: */*
Host: 192.168.0.7
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response... 
---response begin---
HTTP/1.1 401
Server: PsychoPlug
Content-type: text/html
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
Connection: close
WWW-Authenticate: Basic realm="PsychoPlug"

---response end---
401 
Registered socket 3 for persistent reuse.
] done.
Inserted ‘192.168.0.7’ into basic_authed_hosts
Reusing existing connection to 192.168.0.7:443.
Reusing fd 3.

---request begin---
GET /on.html HTTP/1.1
User-Agent: Wget/1.15 (linux-gnu)
Accept: */*
Host: 192.168.0.7
Connection: Keep-Alive
Authorization: Basic YWRtaW46dGVzdGluZw==

---request end---
HTTP request sent, awaiting response... 
---response begin---
---response end---
200 No headers, assuming HTTP/0.9
Length: unspecified
Saving to: ‘on.html.7’

    [ <=>                                   ] 269         --.-K/s   in 0.08s   

2017-05-27 20:57:18 (3.47 KB/s) - ‘on.html.7’ saved [269]

```

**Comment by earlephilhower** [comment]
Errr...if it's geting a connection:close response but reusing the connection still, that's a bug in WGET I think.  Can you try a later wget version?

**Comment by earlephilhower** [comment]
Here's the debug output with the 1.17.1 wget:

earle@server:~$ wget --no-check-certificate --user=admin --password=pass https://192.168.1.36/on.html -O- --verbose --debug
DEBUG output created by Wget 1.17.1 on linux-gnu.

Reading HSTS entries from /home/earle/.wget-hsts
URI encoding = ‘UTF-8’
--2017-05-27 20:52:42--  https://192.168.1.36/on.html
Host ‘192.168.1.36’ has not issued a general basic challenge.
Connecting to 192.168.1.36:443... connected.
Created socket 3.
Releasing 0x0000559994f36190 (new refcount 0).
Deleting unused 0x0000559994f36190.
Initiating SSL handshake.
Handshake successful; connected socket 3 to SSL handle 0x0000559994f361e0
certificate:
  subject: CN=127.0.0.1,O=psychoplug
  issuer:  CN=127.0.0.1,O=psychoplug
WARNING: cannot verify 192.168.1.36's certificate, issued by ‘CN=127.0.0.1,O=psychoplug’:
  Self-signed certificate encountered.
    WARNING: certificate common name ‘127.0.0.1’ doesn't match requested host name ‘192.168.1.36’.

---request begin---
GET /on.html HTTP/1.1
User-Agent: Wget/1.17.1 (linux-gnu)
Accept: */*
Accept-Encoding: identity
Host: 192.168.1.36
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response... 
---response begin---
HTTP/1.1 200 OK
Server: PsychoPlug
Content-type: text/html
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Connection: close
Expires: 0
Refresh: 1; url=index.html

---response end---
200 OK
Length: unspecified [text/html]
Saving to: ‘STDOUT’

-                                                                                                          [<=>                                                                                                                                                                                                                                                                       ]       0  --.-KB/s               <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><html><head><title>Success</title><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
-                                                                                                          [ <=>                                                                                                                                                                                                                                                                      ]     293  --.-KB/s    in 0.03s   

Closed 3/SSL 0x0000559994f361e0
2017-05-27 20:52:42 (9.42 KB/s) - written to stdout [293]

Saving HSTS entries to /home/earle/.wget-hsts

**Comment by ebina1** [comment]
I'm willing to believe it is a bug in wget.  I see online people complaining about what sounds like this same bug in version 1.13
