### ISSUE TITLE
OTA not working

### ISSUE THREAD

**Issue by ebina1** [earlephilhower/psychoplug#5]
I'm trying to use the OTA option to update the firmware over the net.  I'm using Firefox on Windows 7, and I select the .bin file and click the Update button, and after about 3 seconds it gives me an Unable to connect error on IP_address:8080/update

Is OTA supposed to be a working feature?

**Comment by earlephilhower** [comment]
Howdy,

It should work.  It's using the Arduino update class, no changes.  It is destroyed (well, the whole ESP8266 is reset) after 600 seconds, though.  

One gotcha is that you need to make sure you select the 1MB flash size in the IDE, otherwise there's not enough space for the uploaded copy (and I'm not sure exactly how the Arduino code will handle that case)...

```
// globals
static ESP8266HTTPUpdateServer *otaUpdateServer = NULL;

loop() {
...main loop handler...
  } else if (otaServer)  {
    otaServer->handleClient();
  }
... creation of object ...
          otaServer = new ESP8266WebServer(8080);
          otaUpdateServer->setup(otaServer);
          otaServer->begin();

```

**Comment by ebina1** [comment]
So you have tried it and it worked for you?  I did select 1MB size in IDE, and definitely took less than 10 minutes but it isn't working.

**Comment by earlephilhower** [comment]
Yes, in fact I ended up uploading a version with an experimental https OTA update and ended up bricking things on a testing plug.  D'oh.  I'd actually gotten a couple uploads w/o that busted HTTPS updater change fine, so I've seen it work.  Like I said, OTA is handled 100% in the Arduino library code...I simply call its processing loop and it does whatever it does behind the scenes.  I don't even serve that "uplad.html" page, it's coming from the library.

With luck this weekend I'll get some time to solder back the connectors and give the GitHub version a clean build.  Always a chance I've forgotten to check in something, or am not running the version I think I am on the installed plugs.  My fish and landscape lights have been mighty solid for months now, so whatever's going on is definitely solvable...

**Comment by ebina1** [comment]
Another possibility is I messed up the build.  Can you put a .bin file somewhere I can download and try?

**Comment by earlephilhower** [comment]
Howdy,

I just pulled the tree clean from github and built and done a test live upload.  Seemed to work.  Basically, just pick the psychoplug.ino.bin in the /tmp/arduino* directory (one per build) when choosing the upload file.  It's the same thing that you'd send to ESPTOOL.

Here's the BIN I used both to upload via esptool, and then to do via the OTA update:

[compiled.zip](https://github.com/earlephilhower/psychoplug/files/1033812/compiled.zip)

**Comment by ebina1** [comment]
Ok, I got your BIN and uploaded it via esptool.  It loaded, and I set the ssid and password, and when it reset it never connected to wifi.  I wonder if I used the wrong command line options for esptool?
Also when I pull a fresh tree from github and build it does work except OTA still just times out and fails.  This is my first time using Arduino IDE, maybe I have something set wrong?
Board: Generic ESP8266 Module
Flash Mode: DIO
Flash Size: 1M (512K SPIFFS)
Reset Method: ck
Flash Frequency: 40MHz
CPU Frequency: 80MHz

**Comment by earlephilhower** [comment]
That's probably the issue.  Try 64K SPIFFS,  With 512K there's no space for the uploaded version,and it probably just barfs in the SDK code when it sees you trying...

**Comment by ebina1** [comment]
Ok, 64K SPIFFS fixed OTA, at least for .bin files I build.  When I try and load the .bin you use, I still got the problem that I can get to the configuration page where you set ssid and password, but the page loads very very slowly.  And then after I set the network configuration, it never connects to my network.

Could I be using the wrong value for one of those frequency values? It seems like some clock speed is out of sync.

**Comment by earlephilhower** [comment]
The SSL code is pretty slow always, or at least has been that way for me.  Total config page load time on my cellphone attached to the setup AP is around 5-7 seconds (a lot of time spent sending the timezone list, everything else goes pretty fast).  The main control page takes only ~1 second, though, once things are set up and that's fine for my seeds.  W/an underpowered, cooperatively multitasking single-core running the WiFi stack and our code there's not much we can do.

For WiFi connection, that's very odd. One thing you could try is setting a static network config.  Set an IP, netmask (normally 255.255.255.0),  GW, DNS (both your router's IP).  It may be that WiFi isconnected but the DHCP request isn't coming back, which this would solve.  I use DHCP for testing and it's fine, but I move to static IP when I install them permanently.

What ESP8266 library version are you using? I've got 2.3.0 installed ( https://github.com/esp8266/Arduino/releases/download/2.3.0/esp8266-2.3.0.zip ).  Might be some difference there.

Other thing could be power from the USB/serial adaptor.  If you've got a 5V outputand a 3.3V one, I'd recommend the 5V one hooked to the voltage regulator.  5V is normally just pulled straight from the USB port so can handle higher current than most dinky regulators they put on the adaptors...

**Comment by earlephilhower** [comment]
Oh, and your frequencies look fine.  Those are the standard ones, and the ones I use as well.

**Comment by ebina1** [comment]
Ok, I can't get your .bin to work, but with the 64K SPIFFS my own .bin files work fine with OTA now.  So my problem is solved.  Thanks.
