### ISSUE TITLE
WifiServerSecure removed from ESP8266Wifi.h

### ISSUE THREAD

**Issue by cboy2us** [earlephilhower/psychoplug#7]
WifiServerSecure is no longer part of ESP8266Wifi.h. I managed to obtain an older version of the repository where you (Earle) had committed.

**Comment by earlephilhower** [comment]
Howdy,

I think there's some misunderstanding.  It's never been in the main tree, you need to clone the arduino-esp8266 tree and then apply the pull request 3001 to get a working build environment.  So no standard Arduino 

I'm not sure where you got an older version, but if it's not using the above method it's not going to work...

-EFP3

**Comment by earlephilhower** [comment]
Oh, and be sure to get the updated AXTLS from IGRR as well.  I submitted a patch there to save 3K of RAM which is critical if you want a SSL server and a SSL client running at once.

**Comment by cboy2us** [comment]
What I got was from the tree at [https://github.com/esp8266/Arduino/tree/2ae0c295c9a5ee5c210bd5c4579101c42c126cd9]. I misunderstood that was a branch and not master.

**Comment by lodesmets** [comment]
I'm pretty new to installing library's from github. I have installed the master branch from git. How do I apply the pull request 3001?

**Comment by earlephilhower** [comment]
No worries, I have to look it up myself each time, too.  Thanks for checking the issues before filing a new one!

From https://help.github.com/articles/checking-out-pull-requests-locally/
````
git fetch origin pull/3001/head:wifisecureserver
git checkout wifisecureserver
````

Run the above commands in the repo directory and you should end up with the patched copy.  The AXTLS change was already merged.  You can also save memory by using the "-NDEBUG" debugging level (may be called "no asserts" as well).

**Comment by ghost** [comment]
I'm having some trouble trying to figure this out, this is the first time I've used arduino toola.

I got the same error as the OP when trying to compile using the pre-built ESP8266 package. I was able to checkout the wifi patch and create my own package as a zip file but I have no idea how to get it into the board manager.  I even tried putting the extracted contents on a webserver and pointing the URL there. 

Anyone care to tell me what I'm missing?  I've tried to find an answer but no luck.

**Comment by earlephilhower** [comment]
The patch was merged right after 2.4 went out, and is now in GIT head.  Use the esp8266 nightly build, if you want to use a prebuilt setup, or just git clone the esp8266/Arduino repo manually and use that one instead of any .JSON sourced one and you'll get the class.

**Comment by ghost** [comment]
Thanks for the tip!  I was able to get the nightly build easily installed and it worked great. It's really a very nice upgrade for the eco plug!!! :)  One thing I did have to do though is make a change to settings.h psk variable.  I have a long password and it wouldn't accept the whole thing and on reboot would just keep crashing unit I reset it.  Changing it from 32 to 64 allowed it to save the entire password, as confirmed by the confirmation page, and connect.  I can open a new issue for this if it would be best.

**Comment by earlephilhower** [comment]
Sure, you can submit a pull request if you'd like, too.  Just increase the size to 64 where appropriate and I'll do the merge when I get it.  I used a shortened one because of RAM limitations, but with -NDEBUS-NoAssert as the build debug level it should be OK in most operations w/the larger key.
